### ISSUE TITLE
about 

### ISSUE THREAD

**Issue by zhukezhuke** [GeniusWiki/GeniusWiki#2]
in your bulid.xml ,these codes  in it but i can not find them.
<available file="lib/global.xml" property="global.xml.present" /> 
<import file="database-token.xml" />  
      
<import file="lib/global.xml" />  
<import file="lib/global-macro.xml" />

where is the lib/global.xml ,and lib/global-macro.xml?

**Comment by GeniusWiki** [comment]
At ant run, it will download from repo.edgenius.com
